### ISSUE TITLE
How to configure ignore

### ISSUE THREAD

**Issue by Sir0xb** [tcarlsen/atom-htmlhint#10]
I'm using a template. So I want to ignore <at line 1, character 1Doctype must be declared first.>

**Comment by Sir0xb** [comment]
at line 1, character 1Doctype must be declared first.

**Comment by tcarlsen** [comment]
See these two 😄 

https://github.com/yaniswang/HTMLHint/wiki/Doctype-first

https://github.com/yaniswang/HTMLHint/wiki/Usage
