### ISSUE TITLE
custom keymap sector error

### ISSUE THREAD

**Issue by stephanfriedrich** [tcarlsen/atom-htmlhint#6]
Hi, your Keybinding-Sector throws an error, if i paste it in my keymap.cson

Atom -v: 1.0.2-9432598

*ERROS:*
```
[stdin]:9:33: error: unexpected text
'atom-text-editor[data-grammar='text html basic']':
                                ^^^^
```

**Comment by tcarlsen** [comment]
Thx fir reporting

**Comment by tcarlsen** [comment]
the right keybinding is `"atom-text-editor[data-grammar='text html basic']":` 

You have single quotes inside single quotes. :wink:
