### ISSUE TITLE
Suppress a DTD warning.

### ISSUE THREAD

**Issue by aqeelb** [tcarlsen/atom-htmlhint#8]
Is there any way to suppress the DTD warning / add an exception they way we do with JSLint?

<img width="484" alt="screen shot 2015-10-13 at 5 34 18 pm" src="https://cloud.githubusercontent.com/assets/2950322/10451105/b4ba60a2-71d0-11e5-9a43-00f4ded4b87b.png">

My apologies I accidently added this question to your csslint repository. :-1:

**Comment by tcarlsen** [comment]
yes you can add a `.htmlhintrc` file at the root of your project with `"doctype-html5": false`

see https://github.com/yaniswang/HTMLHint/wiki/Rules for more information
